from Environment import *
from Architecture import *

mm = MazeMan(Maze())

#print(mm.get_actions())
print(mm.interact({'walk': 'up'}))
print(mm.get_actions())
print(mm.interact({'walk': 'up'}))
print(mm.get_actions())
print(mm.interact({'walk': 'up'}))
print(mm.get_actions())
print(mm.interact({'walk': 'up'}))
print(mm.get_actions())
print(mm.interact({'walk': 'right'}))
print(mm.get_actions())
print(mm.interact({'walk': 'right'}))
print(mm.get_actions())
print(mm.interact({'walk': 'right'}))
print(mm.get_actions())
print(mm.interact({'walk': 'right'}))
print(mm.get_actions())
print(mm.interact({'walk': 'down'}))
print(mm.get_actions())
print(mm.interact({'walk': 'down'}))
print(mm.get_actions())
print(mm.interact({'walk': 'right'}))
print(mm.get_actions())
print(mm.interact({'walk': 'right'}))
print(mm.get_actions())
print(mm.interact({'walk': 'up'}))
print(mm.get_actions())
print(mm.interact({'walk': 'right'}))
print(mm.get_actions())
print(mm.interact({'walk': 'up'}))
print(mm.get_actions())
print(mm.interact({'walk': 'up'}))
print(mm.get_actions())
print(mm.interact({'walk': 'up'}))
print(mm.get_actions())
print(mm.interact({'walk': 'up'}))
print(mm.get_actions())
print(mm.interact({'walk': 'up'}))
print(mm.get_actions())
print(mm.interact({'walk': 'right'}))
print(mm.get_actions())